### ISSUE TITLE
Package polishing checklist

### ISSUE THREAD

**Issue by edwardlavender** [scheidan/Wahoo.jl#11]
Checklist of things to do before making Wahoo.jl available: 

- [ ] add citation
- [ ] check doc strings
- [ ] document usage with an example
- [ ] link or add example data?
- [ ] make repo public
- [ ] register as Julia package

**Comment by scheidan** [comment]
done
